services:
  front:
    build:
     context: .
     dockerfile: Dockerfile
    depends_on:
      psql-template:
        condition: service_healthy
      consul:
        condition: service_healthy  

    command: java -jar -agentlib:jdwp=transport=dt_socket,address=*:8088,server=y,suspend=n front.mybank.jar
    
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
    ports:
      - "8080:8080"
      - "8088:8088"
    networks:
      - nest

  psql-template:
    build:
      context: ../
      dockerfile: Dockerfile.psql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATASOURCE_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5      
    environment:
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - nest

  consul:
    image: consul:1.15.4
    ports:
      - "8500:8500"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://consul:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: ["consul", "agent", "-server", "-ui", "-bind", "0.0.0.0", "-client", "0.0.0.0", "-data-dir", "/consul/data", "-config-dir", "/consul/config"]
    volumes:
      - ../consul/data:/consul/data
      - ../consul/config:/consul/config  
    networks:
      - nest

volumes:
  postgres_data:
    external: false 
  postgres_data_keycloak:
    external: false

networks:
  nest:
