FROM postgres:latest

ENV PGDATA=/var/lib/postgresql/data/pgdata

RUN sed -i '/ru_RU.UTF-8/s/^# //g' /etc/locale.gen && \
    locale-gen

RUN locale-gen "ru_RU.UTF-8"

ENV LC_ALL="ru_RU.UTF-8"
ENV LANG=ru_RU.UTF-8
ENV LANGUAGE=ru_RU.UTF-8

COPY "db/db-keycloak.sql" "/docker-entrypoint-initdb.d"