server:
    port: 8080
    servlet:
        context-path: /template

spring:
    application:
        name: template
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    liquibase:
        default-schema: templatescheme
        liquibase-schema: public

    cloud:
        consul:
            host: consul
            port: 8500
            discovery:
                enabled: true
                service-name: template
                instance-id: ${spring.application.name}:${random.value}
                health-check-path: /actuator/health
                health-check-interval: 15s
                heartbeat:
                    enabled: true

    jpa:
        show-sql: false    
        hibernate:
            ddl-auto: none    
        properties:
            hibernate:
                '[format_sql]': false
