server:
    port: 8080
    servlet:
        context-path: /template

spring:
    application:
        name: template
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver

    jpa:
        show-sql: false    
        hibernate:
            default_schema: templatescheme
            ddl-auto: none    
        properties:
            hibernate:
                default_schema: templatescheme
                '[format_sql]': false
