server:
    port: 8080
    servlet:
        context-path: /template

spring:
    application:
        name: template
    datasource:
        url: ${DATASOURCE_URL}
        username: ${DATASOURCE_USER}
        password: ${DATASOURCE_PASSWORD}
        driver-class-name: org.postgresql.Driver
    liquibase:
        default-schema: templatescheme
        liquibase-schema: public

    jpa:
        show-sql: false    
        hibernate:
            ddl-auto: none    
        properties:
            hibernate:
                '[format_sql]': false
