spring:
  application:
        name: gateway
  config:
    import: 'optional:consul:'
  cloud:
    consul:
      host: consul
      port: 8500
      config:
        enabled: true
        format: YAML
        prefixes: config
        data-key: data
        watch:
          enabled: true
